apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Release.Namespace }}
data:
  configuration.yaml: |
{{ .Files.Get "configuration.yaml" | indent 4 }}
  automations.yaml: |
{{ .Files.Get "automations.yaml" | indent 4 }}
  alexa.yaml: |
{{ .Files.Get "alexa.yaml" | indent 4 }}
  scenes.yaml: |
{{ .Files.Get "scenes.yaml" | indent 4 }}
  scripts.yaml: |
{{ .Files.Get "scripts.yaml" | indent 4 }}
  home-dashboard.yaml: |
{{ .Files.Get "home-dashboard.yaml" | indent 4 }}
  wohnzimmer-dashboard.yaml: |
{{ .Files.Get "wohnzimmer-dashboard.yaml" | indent 4 }}
  szenen-dashboard.yaml: |
{{ .Files.Get "szenen-dashboard.yaml" | indent 4 }}
  klima-dashboard.yaml: |
{{ .Files.Get "klima-dashboard.yaml" | indent 4 }}
  sicherheit-dashboard.yaml: |
{{ .Files.Get "sicherheit-dashboard.yaml" | indent 4 }}
  medien-dashboard.yaml: |
{{ .Files.Get "medien-dashboard.yaml" | indent 4 }}
  system-dashboard.yaml: |
{{ .Files.Get "system-dashboard.yaml" | indent 4 }}
