# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  dashboards:
    lovelace-home:
      mode: yaml
      filename: home-dashboard.yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
    lovelace-wohnzimmer:
      mode: yaml
      filename: wohnzimmer-dashboard.yaml
      title: Wohnzimmer
      icon: mdi:sofa
      show_in_sidebar: true

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
alexa: !include alexa.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8
    - 127.0.0.1
    - ::1
api:
