version: '1.0'
smartHome:
  conditions:
  - type: SpelExpression
    id: day
    expression: '#timeOfDay() == ''DAY'''
  - type: SpelExpression
    id: night
    expression: '#timeOfDay() == ''NIGHT'''
  homeAssistantResources:
  - type: Light
    id: light_buero_jonas
    lookups:
    - type: staticEntity
      entityRefs:
      - light.buero_jonas
  - type: Light
    id: light_buero_lena
    lookups:
    - type: staticEntity
      entityRefs:
      - light.buero_lena
  - type: Light
    id: light_esszimmer
    lookups:
    - type: staticEntity
      entityRefs:
      - light.esszimmer
  - type: Light
    id: light_gaestezimmer
    lookups:
    - type: staticEntity
      entityRefs:
      - light.gaestezimmer
  - type: Light
    id: light_schlafzimmer
    lookups:
    - type: staticEntity
      entityRefs:
      - light.schlafzimmer
  - type: Light
    id: light_treppe_dach
    lookups:
    - type: staticEntity
      entityRefs:
      - light.treppe_dach
  - type: Light
    id: light_treppe_keller
    lookups:
    - type: staticEntity
      entityRefs:
      - light.treppe_keller
  - type: Light
    id: light_treppe_oben
    lookups:
    - type: staticEntity
      entityRefs:
      - light.treppe_oben
  - type: Scene
    id: Schlafzimmer__DimmerSwitch__01__day
    lookups:
    - type: labelRegex
      labelRegex: Schlafzimmer__DimmerSwitch__01__day__.*
  - type: Scene
    id: Schlafzimmer__DimmerSwitch__01__nigt
    lookups:
    - type: labelRegex
      labelRegex: Schlafzimmer__DimmerSwitch__01__night__.*
  sensors:
  - name: Schlafzimmer
    type: HueDimmerSwitch
    devices:
    - S50
    groups:
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Schlafzimmer__DimmerSwitch__01__day
          condition: day
        - homeAssistantResources:
          - Schlafzimmer__DimmerSwitch__01__nigt
          condition: night
      homeAssistantResources:
      - light_schlafzimmer
